# Generated by Django 3.1.2 on 2020-10-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
